apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springforge-backend-monitor
  namespace: springforge
  labels:
    app.kubernetes.io/name: springforge-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: springforge-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - springforge
