# ADR-001: Architecture Choice — ${architecture!"Hexagonal"}

## Status

Accepted

## Context

The team needed to choose an architecture pattern for ${projectName} that supports:
- Clear separation of concerns
- Testability of business logic in isolation
- Independence from frameworks and infrastructure
- Long-term maintainability as the codebase grows

## Decision

We chose **${architecture!"Hexagonal"}** architecture for this project.

<#if architecture?? && architecture == "HEXAGONAL">
The domain layer defines ports (interfaces) that are implemented by adapters in the infrastructure layer. The application layer orchestrates use cases by calling domain services through these ports.
<#elseif architecture?? && architecture == "DDD">
We model the domain using Aggregates, Value Objects, Domain Events, and Repositories. Each bounded context has clear boundaries and communicates via domain events.
<#elseif architecture?? && architecture == "CQRS">
Commands and Queries are handled by separate models, allowing independent optimization of read and write paths.
<#else>
The chosen pattern best fits our team's expertise and the complexity of the domain.
</#if>

## Consequences

### Positive
- Business logic is testable without infrastructure dependencies
- Easy to swap infrastructure components (database, messaging, etc.)
- Clear boundaries guide new developers

### Negative
- More boilerplate code compared to simple layered architecture
- Steeper learning curve for developers unfamiliar with the pattern

## References

- Generated by SpringForge on ${.now?string("yyyy-MM-dd")}
