package wizard

import (
	"fmt"
	"strings"

	"github.com/landry1996/springforge-cli/internal/config"
	"github.com/manifoldco/promptui"
)

func RunWizard() (*config.ProjectConfiguration, error) {
	cfg := &config.ProjectConfiguration{}

	groupID, err := promptText("Group ID", "com.example")
	if err != nil {
		return nil, err
	}
	cfg.Metadata.GroupID = groupID

	artifactID, err := promptText("Artifact ID", "my-app")
	if err != nil {
		return nil, err
	}
	cfg.Metadata.ArtifactID = artifactID

	name, err := promptText("Project Name", artifactID)
	if err != nil {
		return nil, err
	}
	cfg.Metadata.Name = name

	description, err := promptText("Description", "Spring Boot application generated by SpringForge")
	if err != nil {
		return nil, err
	}
	cfg.Metadata.Description = description

	packageName, err := promptText("Package Name", groupID+"."+strings.ReplaceAll(artifactID, "-", ""))
	if err != nil {
		return nil, err
	}
	cfg.Metadata.PackageName = packageName

	javaVersion, err := promptSelect("Java Version", []string{"21", "17", "11"})
	if err != nil {
		return nil, err
	}
	cfg.Metadata.JavaVersion = javaVersion

	springBootVersion, err := promptSelect("Spring Boot Version", []string{"3.3.5", "3.2.12", "3.1.12"})
	if err != nil {
		return nil, err
	}
	cfg.Metadata.SpringBootVersion = springBootVersion

	buildTool, err := promptSelect("Build Tool", []string{"MAVEN", "GRADLE"})
	if err != nil {
		return nil, err
	}
	cfg.Metadata.BuildTool = buildTool

	archType, err := promptSelect("Architecture", []string{
		"MONOLITHIC",
		"LAYERED",
		"HEXAGONAL",
		"DDD",
		"CQRS",
		"EVENT_DRIVEN",
		"MICROSERVICES",
		"MODULITH",
	})
	if err != nil {
		return nil, err
	}
	cfg.Architecture.Type = archType

	if archType == "MODULITH" || archType == "MICROSERVICES" {
		modules, err := promptText("Modules (comma-separated)", "user,order,payment")
		if err != nil {
			return nil, err
		}
		cfg.Architecture.Modules = splitAndTrim(modules)
	}

	enableObservability, err := promptConfirm("Enable Observability (metrics, tracing, logging)?")
	if err != nil {
		return nil, err
	}
	if enableObservability {
		cfg.Observability = &config.ObservabilityConfig{
			Enabled:           true,
			Metrics:           true,
			Tracing:           true,
			StructuredLogging: true,
		}
	}

	enableSecurity, err := promptConfirm("Enable Security (OAuth2/OIDC)?")
	if err != nil {
		return nil, err
	}
	if enableSecurity {
		provider, err := promptSelect("Security Provider", []string{"keycloak", "okta", "auth0"})
		if err != nil {
			return nil, err
		}
		cfg.Security = &config.SecurityConfig{
			Enabled:  true,
			Type:     "OAUTH2",
			Provider: provider,
		}
	}

	enableMessaging, err := promptConfirm("Enable Kafka Messaging?")
	if err != nil {
		return nil, err
	}
	if enableMessaging {
		topics, err := promptText("Kafka Topics (comma-separated)", "events,commands")
		if err != nil {
			return nil, err
		}
		cfg.Messaging = &config.MessagingConfig{
			Type:   "KAFKA",
			Topics: splitAndTrim(topics),
		}
	}

	enableDocker, err := promptConfirm("Generate Docker & Helm?")
	if err != nil {
		return nil, err
	}
	if enableDocker {
		cfg.Infrastructure = &config.InfrastructureConfig{
			Docker: true,
			Helm:   true,
			CI:     true,
		}
	}

	return cfg, nil
}

func promptText(label, defaultVal string) (string, error) {
	prompt := promptui.Prompt{
		Label:   label,
		Default: defaultVal,
	}
	result, err := prompt.Run()
	if err != nil {
		return "", fmt.Errorf("prompt cancelled: %w", err)
	}
	return result, nil
}

func promptSelect(label string, items []string) (string, error) {
	prompt := promptui.Select{
		Label: label,
		Items: items,
	}
	_, result, err := prompt.Run()
	if err != nil {
		return "", fmt.Errorf("prompt cancelled: %w", err)
	}
	return result, nil
}

func promptConfirm(label string) (bool, error) {
	prompt := promptui.Select{
		Label: label,
		Items: []string{"Yes", "No"},
	}
	_, result, err := prompt.Run()
	if err != nil {
		return false, fmt.Errorf("prompt cancelled: %w", err)
	}
	return result == "Yes", nil
}

func splitAndTrim(s string) []string {
	parts := strings.Split(s, ",")
	result := make([]string, 0, len(parts))
	for _, p := range parts {
		trimmed := strings.TrimSpace(p)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}
