apiVersion: v1
kind: Secret
metadata:
  name: springforge-secrets
  namespace: springforge
  labels:
    app.kubernetes.io/name: springforge
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "springforge"
  SPRING_DATASOURCE_PASSWORD: "changeme-in-production"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://auth.springforge.io/realms/springforge"
